# Generated by Django 6.0.5 on 2026-05-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='blog/covers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='palette',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
