# Generated by Django 6.0.5 on 2026-06-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_alter_blogpost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.TextField(blank=True)),
                ('phone_display', models.CharField(blank=True, max_length=50)),
                ('phone_href', models.CharField(blank=True, max_length=50)),
                ('secondary_phone_display', models.CharField(blank=True, max_length=50)),
                ('secondary_phone_href', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('service_area', models.TextField(blank=True)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='site/')),
                ('hero', models.FileField(blank=True, null=True, upload_to='site/')),
                ('hero_slides', models.JSONField(blank=True, default=list)),
                ('about', models.FileField(blank=True, null=True, upload_to='site/')),
                ('services', models.FileField(blank=True, null=True, upload_to='site/')),
                ('projects', models.FileField(blank=True, null=True, upload_to='site/')),
                ('contact', models.FileField(blank=True, null=True, upload_to='site/')),
                ('team', models.FileField(blank=True, null=True, upload_to='site/')),
                ('structural', models.FileField(blank=True, null=True, upload_to='site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
